
---
author: "Lawrence Koerner"
title: "DecisionTree"
date: "September 24, 2018"
output: html_notebook
---

#Reading Data
```{r}
wine <- read.table("http://mlr.cs.umass.edu/ml/machine-learning-databases/wine/wine.data", sep= ",")
names(wine) <- c("Class","Alcohol", "Malic.Acid", "Ash", "Alcalinity.of.Ash", "Magnesium", "Total.Phenols", "Flavanoids", "Nonflavanoid.Phenols", "Proanthocyanins", "Color.Intensity", "Hue", "Diluted.Wines.Measure", "Proline") 

head(wine)
```


#Building a model
```{r}
library(rpart.plot)
library(rpart)

#create decision tree
tree <- rpart(Class ~Alcohol + Malic.Acid + Ash + Alcalinity.of.Ash + Magnesium + Total.Phenols + Flavanoids + Nonflavanoid.Phenols + Proanthocyanins + Color.Intensity + Hue + Diluted.Wines.Measure +Proline, data=wine, method='class')
#show decision tree
prp(tree, type=1, extra=1)
#create confusion table
tab <- table(data.frame(wine$Class, pred=predict(tree, type ="class")))
tab
#show accuracy
sum(diag(tab))/sum(tab)


```


#scatterplot
```{r}
library(ggplot2)
#creat scatterplot with title, labels, and legend
qplot(data=wine, x=Alcalinity.of.Ash, y=Flavanoids, color=Class, main="Alcalinity of Ash vs Flavanoids")
```

